/**
 * TypeScript projection of `mncs/pack.mncs` (`scratchtrack.pack.v1`).
 *
 * Exact integer ZIP-store layout math: fixed-field offsets, sizes,
 * signatures, and entry-walk arithmetic for the uncompressed project
 * pack. Byte access stays host-side at the boundary; iteration over
 * dynamic structures (backward EOCD scan, per-entry walk) stays
 * host-side too (see P-009/P-012 in docs/mncs-pressure.md). Checksums
 * moved to the MNCS CRC model (`mncs/crc.mncs` / `mncsCrc.ts`), which the
 * pack writer delegates to.
 *
 * Every kernel runs its compiled MNCS function WASM-first (via
 * `wasmFirst`) with the pure body below as the conformance-pinned
 * fallback. Window-taking kernels slice the semantically-correct fixed
 * window (46-byte local/central, 22-byte EOCD) out of the host buffer;
 * when fewer bytes remain, the pure body runs instead (same value).
 * MNCS is the semantic authority: `mncs/pack.mncs` plus
 * `mncs/pack-corpus.json` (generated by `scripts/mncs-pack-corpus.py`)
 * define the contract, `src/mncsPack.test.ts` pins every corpus vector in
 * this suite, and `scripts/mncs-evidence.sh` replays the proof through
 * the MNCS toolchain. Any intentional divergence is a bug in this file,
 * never in MNCS source.
 */

import {
  wasmFirst,
  wasmPackCentralEntry,
  wasmPackLeU16At,
  wasmPackLeU32At,
  wasmPackCentralNext,
  wasmPackCentralRecordSize,
  wasmPackCentralSignatureOk,
  wasmPackEocdCentralOffset,
  wasmPackEocdCentralSize,
  wasmPackEocdCount,
  wasmPackEocdSignatureOk,
  wasmPackLocalDataSize,
  wasmPackLocalDataStart,
  wasmPackLocalExtraLen,
  wasmPackLocalNameLen,
  wasmPackLocalRecordSize,
  wasmPackLocalSignatureOk,
  type WasmPackEntry,
} from './mncsWasm';

/** ZIP structural constants owned by MNCS. */
export const ZIP_LOCAL_SIGNATURE = 0x04034b50;
export const ZIP_CENTRAL_SIGNATURE = 0x02014b50;
export const ZIP_EOCD_SIGNATURE = 0x06054b50;
export const ZIP_LOCAL_HEADER_SIZE = 30;
export const ZIP_CENTRAL_HEADER_SIZE = 46;
export const ZIP_EOCD_SIZE = 22;

/** Local fixed-field offsets (30-byte header). */
export const ZIP_LOCAL_NAME_LEN_OFFSET = 26;
export const ZIP_LOCAL_EXTRA_LEN_OFFSET = 28;
export const ZIP_LOCAL_DATA_SIZE_OFFSET = 22;
/** Central fixed-field offsets (46-byte record). */
export const ZIP_CENTRAL_CRC_OFFSET = 16;
export const ZIP_CENTRAL_DATA_SIZE_OFFSET = 24;
export const ZIP_CENTRAL_NAME_LEN_OFFSET = 28;
export const ZIP_CENTRAL_EXTRA_LEN_OFFSET = 30;
export const ZIP_CENTRAL_COMMENT_LEN_OFFSET = 32;
export const ZIP_CENTRAL_LOCAL_OFFSET_OFFSET = 42;
/** EOCD fixed-field offsets. */
export const ZIP_EOCD_COUNT_OFFSET = 10;
export const ZIP_EOCD_SIZE_OFFSET = 12;
export const ZIP_EOCD_OFFSET_OFFSET = 16;

/** Structured central-directory entry: mirrors MNCS record `Entry`. */
export interface PackEntry {
  nameLen: number;
  extraLen: number;
  commentLen: number;
  localOffset: number;
  dataSize: number;
  crc: number;
}

/** Slice `len` bytes at `at` (null when the buffer ends first). */
function sliceWindow(view: DataView, at: number, len: number): Uint8Array | null {
  if (at < 0 || at + len > view.byteLength) return null;
  return new Uint8Array(view.buffer, view.byteOffset + at, len);
}

/** MNCS `le16_46` / `le32_46` (local + central windows). */
export function mncsPackLe16(view: DataView, offset: number): number {
  // The staged window starts at `offset`, so the intra-window offset is 0.
  const window = sliceWindow(view, offset, ZIP_CENTRAL_HEADER_SIZE);
  return wasmFirst('le16_46', window ? wasmPackLeU16At(window, 0) : null, () => (
    view.getUint8(offset) + view.getUint8(offset + 1) * 256
  ));
}

export function mncsPackLe32(view: DataView, offset: number): number {
  const window = sliceWindow(view, offset, ZIP_CENTRAL_HEADER_SIZE);
  return wasmFirst('le32_46', window ? wasmPackLeU32At(window, 0) : null, () => (
    view.getUint8(offset) +
    view.getUint8(offset + 1) * 256 +
    view.getUint8(offset + 2) * 65536 +
    view.getUint8(offset + 3) * 16777216
  ));
}

/** MNCS `local_signature_ok`. */
export function mncsLocalSignatureOk(view: DataView, offset: number): boolean {
  const window = sliceWindow(view, offset, ZIP_CENTRAL_HEADER_SIZE);
  return wasmFirst('local_signature_ok', window ? wasmPackLocalSignatureOk(window) : null, () => (
    mncsPackLe32(view, offset) === ZIP_LOCAL_SIGNATURE
  ));
}

/** MNCS `local_name_len` / `local_extra_len` / `local_data_size`. */
export function mncsLocalNameLen(view: DataView, offset: number): number {
  const window = sliceWindow(view, offset, ZIP_CENTRAL_HEADER_SIZE);
  return wasmFirst('local_name_len', window ? wasmPackLocalNameLen(window) : null, () => (
    mncsPackLe16(view, offset + ZIP_LOCAL_NAME_LEN_OFFSET)
  ));
}

export function mncsLocalExtraLen(view: DataView, offset: number): number {
  const window = sliceWindow(view, offset, ZIP_CENTRAL_HEADER_SIZE);
  return wasmFirst('local_extra_len', window ? wasmPackLocalExtraLen(window) : null, () => (
    mncsPackLe16(view, offset + ZIP_LOCAL_EXTRA_LEN_OFFSET)
  ));
}

export function mncsLocalDataSize(view: DataView, offset: number): number {
  const window = sliceWindow(view, offset, ZIP_CENTRAL_HEADER_SIZE);
  return wasmFirst('local_data_size', window ? wasmPackLocalDataSize(window) : null, () => (
    mncsPackLe32(view, offset + ZIP_LOCAL_DATA_SIZE_OFFSET)
  ));
}

/** MNCS `local_data_start` / `local_record_size` (u64 scalars). */
export function mncsLocalDataStart(localOffset: number, nameLen: number, extraLen: number): number {
  return wasmFirst('local_data_start', wasmPackLocalDataStart(localOffset, nameLen, extraLen), () => (
    localOffset + ZIP_LOCAL_HEADER_SIZE + nameLen + extraLen
  ));
}

export function mncsLocalRecordSize(nameLen: number, dataLen: number): number {
  return wasmFirst('local_record_size', wasmPackLocalRecordSize(nameLen, dataLen), () => (
    ZIP_LOCAL_HEADER_SIZE + nameLen + dataLen
  ));
}

/** MNCS `central_signature_ok`. */
export function mncsCentralSignatureOk(view: DataView, offset: number): boolean {
  const window = sliceWindow(view, offset, ZIP_CENTRAL_HEADER_SIZE);
  return wasmFirst('central_signature_ok', window ? wasmPackCentralSignatureOk(window) : null, () => (
    mncsPackLe32(view, offset) === ZIP_CENTRAL_SIGNATURE
  ));
}

/** MNCS `central_entry` (Entry record return). */
export function mncsCentralEntry(view: DataView, offset: number): PackEntry {
  const window = sliceWindow(view, offset, ZIP_CENTRAL_HEADER_SIZE);
  return wasmFirst<WasmPackEntry>('central_entry', window ? wasmPackCentralEntry(window) : null, () => ({
    nameLen: mncsPackLe16(view, offset + ZIP_CENTRAL_NAME_LEN_OFFSET),
    extraLen: mncsPackLe16(view, offset + ZIP_CENTRAL_EXTRA_LEN_OFFSET),
    commentLen: mncsPackLe16(view, offset + ZIP_CENTRAL_COMMENT_LEN_OFFSET),
    localOffset: mncsPackLe32(view, offset + ZIP_CENTRAL_LOCAL_OFFSET_OFFSET),
    dataSize: mncsPackLe32(view, offset + ZIP_CENTRAL_DATA_SIZE_OFFSET),
    crc: mncsPackLe32(view, offset + ZIP_CENTRAL_CRC_OFFSET),
  }));
}

/** MNCS `central_next` / `central_record_size` (u64 scalars). */
export function mncsCentralNext(central: number, nameLen: number, extraLen: number, commentLen: number): number {
  return wasmFirst(
    'central_next',
    wasmPackCentralNext(central, nameLen, extraLen, commentLen),
    () => central + ZIP_CENTRAL_HEADER_SIZE + nameLen + extraLen + commentLen,
  );
}

export function mncsCentralRecordSize(nameLen: number): number {
  return wasmFirst('central_record_size', wasmPackCentralRecordSize(nameLen), () => (
    ZIP_CENTRAL_HEADER_SIZE + nameLen
  ));
}

/** MNCS EOCD readers over a 22-byte window. */
export function mncsEocdSignatureOk(view: DataView, offset: number): boolean {
  const window = sliceWindow(view, offset, ZIP_EOCD_SIZE);
  return wasmFirst('eocd_signature_ok', window ? wasmPackEocdSignatureOk(window) : null, () => (
    mncsPackLe32Eocd(view, offset) === ZIP_EOCD_SIGNATURE
  ));
}

export function mncsEocdCount(view: DataView, offset: number): number {
  const window = sliceWindow(view, offset, ZIP_EOCD_SIZE);
  return wasmFirst('eocd_count', window ? wasmPackEocdCount(window) : null, () => (
    mncsPackLe16Eocd(view, offset + ZIP_EOCD_COUNT_OFFSET)
  ));
}

export function mncsEocdCentralSize(view: DataView, offset: number): number {
  const window = sliceWindow(view, offset, ZIP_EOCD_SIZE);
  return wasmFirst('eocd_central_size', window ? wasmPackEocdCentralSize(window) : null, () => (
    mncsPackLe32Eocd(view, offset + ZIP_EOCD_SIZE_OFFSET)
  ));
}

export function mncsEocdCentralOffset(view: DataView, offset: number): number {
  const window = sliceWindow(view, offset, ZIP_EOCD_SIZE);
  return wasmFirst('eocd_central_offset', window ? wasmPackEocdCentralOffset(window) : null, () => (
    mncsPackLe32Eocd(view, offset + ZIP_EOCD_OFFSET_OFFSET)
  ));
}

/** MNCS `eocd_size`. */
export function mncsEocdSize(): number {
  return ZIP_EOCD_SIZE;
}

/* Raw readers for EOCD windows (22 bytes — no 46-byte window exists). */
function mncsPackLe16Eocd(view: DataView, offset: number): number {
  return view.getUint8(offset) + view.getUint8(offset + 1) * 256;
}

function mncsPackLe32Eocd(view: DataView, offset: number): number {
  return (
    view.getUint8(offset) +
    view.getUint8(offset + 1) * 256 +
    view.getUint8(offset + 2) * 65536 +
    view.getUint8(offset + 3) * 16777216
  );
}
