/**
 * TypeScript projection of `mncs/geometry.mncs` (`scratchtrack.geometry.v1`).
 *
 * Exact integer visual-domain and pointer-interpretation math over whole
 * units (steps, ticks, pixels, MIDI notes). Rendering (DOM/SVG layout,
 * colors, text) and trig positioning (drum-orbit cos/sin) stay host-side:
 * MNCS has no float or trig vocabulary yet (see P-001 and P-008 in
 * docs/mncs-pressure.md).
 *
 * MNCS is the semantic authority: `mncs/geometry.mncs` plus
 * `mncs/geometry-corpus.json` (generated by
 * `scripts/mncs-geometry-corpus.py`) define the contract,
 * `src/mncsGeometry.test.ts` pins every corpus vector in this suite, and
 * `scripts/mncs-evidence.sh` replays the proof through the MNCS toolchain.
 * Any intentional divergence is a bug in this file, never in MNCS source.
 */

/** Whole-sample waveform bucket window: mirrors MNCS record `Bounds`. */
export interface SampleBounds {
  start: number;
  end: number;
}

/** MNCS `is_beat_step`: beat-marker classification for drum views. */
export function mncsIsBeatStep(step: number, stepsPerBeat: number): boolean {
  if (stepsPerBeat <= 0) return false;
  return step % stepsPerBeat === 0;
}

/**
 * MNCS `swing_applies`: swing-delay phase. The host maps the subdivision
 * label to `isTriplet` (MNCS has no strings yet).
 */
export function mncsSwingApplies(isTriplet: boolean, step: number): boolean {
  return isTriplet ? step % 3 === 2 : step % 2 === 1;
}

/**
 * MNCS `steps_per_beat`: round-half-up(steps/numerator), at least 1.
 * Exact for non-negative inputs: a single correctly-rounded division
 * whose ties are representable (see the row-delta note below).
 */
export function mncsStepsPerBeat(steps: number, numerator: number): number {
  const denom = numerator < 1 ? 1 : numerator;
  const spaced = Math.trunc((2 * steps + denom) / (2 * denom));
  return spaced < 1 ? 1 : spaced;
}

/** MNCS `cycle_cell`: DrumCell tap → hit → accent → tap. */
export function mncsCycleCell(cell: number): number {
  return (cell + 1) % 3;
}

/** MNCS `advance_step`: pattern preview advance with wraparound. */
export function mncsAdvanceStep(step: number, steps: number): number {
  if (steps <= 0) return 0;
  return (step + 1) % steps;
}

/**
 * MNCS `floor_div`: floor division for a positive divisor. MNCS `/`
 * truncates toward zero, which misplaces negative grid offsets by one;
 * visual grids need floor. Precondition: denominator > 0.
 */
export function mncsFloorDiv(numerator: number, denominator: number): number {
  const quotient = Math.trunc(numerator / denominator);
  const remainder = numerator % denominator;
  // `%` truncates like MNCS: a negative remainder means truncation rounded
  // up, so step one down to reach the floor.
  return remainder < 0 ? quotient - 1 : quotient;
}

/**
 * MNCS `row_delta`: piano-roll row count for a vertical pointer drag.
 * Mirrors Math.round(dy / rowH) exactly for all integer pixels: one
 * correctly-rounded division whose tie values are exactly representable,
 * with non-tie rationals keeping distance ≥ 1/(2·rowH) from boundaries
 * while float error stays under one ulp. Precondition: rowH > 0.
 */
export function mncsRowDelta(dyPx: number, rowH: number): number {
  return mncsFloorDiv(dyPx * 2 + rowH, 2 * rowH);
}

/**
 * MNCS `drag_started`: 5px horizontal or full-row vertical movement ends
 * the tap grace. Mirrors `!(|dx| < 5 && |dy| < 1)` over integers.
 */
export function mncsDragStarted(dxPx: number, dyRows: number): boolean {
  return dxPx >= 5 || dxPx <= -5 || dyRows >= 1 || dyRows <= -1;
}

/**
 * MNCS `tap_cancelled`: pointer wandered more than 6px on either axis.
 * Mirrors `|dx| > 6 || |dy| > 6` over integers.
 */
export function mncsTapCancelled(dxPx: number, dyPx: number): boolean {
  return dxPx > 6 || dxPx < -6 || dyPx > 6 || dyPx < -6;
}

/** MNCS `clamp_motif_midi`: motif range C1..C8 (12..108). */
export function mncsClampMotifMidi(midi: number): number {
  if (midi < 12) return 12;
  if (midi > 108) return 108;
  return midi;
}

/** MNCS `shift_motif_midi`: shifted motif note kept in range. */
export function mncsShiftMotifMidi(midi: number, delta: number): number {
  return mncsClampMotifMidi(midi + delta);
}

/**
 * MNCS `pick_row_midi`: MIDI note for a piano-roll row, clamped into
 * range and counted down from `hi`. Precondition: rowCount >= 1.
 */
export function mncsPickRowMidi(hi: number, row: number, rowCount: number): number {
  const last = rowCount - 1;
  const clamped = row < 0 ? 0 : row > last ? last : row;
  return hi - clamped;
}

/**
 * MNCS `half_beatline_count`: half-beat grid lines below a motif span of
 * `motifTicks` ticks. The host converts beats→ticks at the float edge.
 */
export function mncsHalfBeatlineCount(motifTicks: number): number {
  if (motifTicks <= 0) return 0;
  return Math.trunc((motifTicks + 11) / 12);
}

/**
 * MNCS `bucket_bounds`: waveform sample window for a bucket. The host
 * keeps the float peak loop; partitioning is owned here.
 */
export function mncsBucketBounds(length: number, bucket: number, count: number): SampleBounds {
  // Math.trunc mirrors MNCS `/` truncation (non-negative here, so floor).
  const size = Math.trunc(length / count);
  const sized = size < 1 ? 1 : size;
  const start = bucket * sized;
  const end = start + sized < length ? start + sized : length;
  return { start, end };
}

/** MNCS `bucket_stride`: peak-sampling stride capped at ~90 reads/bucket. */
export function mncsBucketStride(start: number, end: number): number {
  const stride = Math.trunc((end - start) / 90);
  return stride < 1 ? 1 : stride;
}
