/**
 * TypeScript projection of `mncs/migrate.mncs` (`scratchtrack.migrate.v1`).
 *
 * Exact integer project-migration math for v1/v2/v3 → v4 documents.
 * String/structure traversal (track kinds, settings objects, pattern
 * arrays) stays host-side; positions, counts, and policy live here.
 *
 * Every kernel runs its compiled MNCS function WASM-first (via
 * `wasmFirst`) with the pure body below as the conformance-pinned
 * fallback. MNCS is the semantic authority: `mncs/migrate.mncs` plus
 * `mncs/migrate-corpus.json` (generated by
 * `scripts/mncs-migrate-corpus.py`) define the contract,
 * `src/mncsMigrate.test.ts` pins every corpus vector in this suite, and
 * `scripts/mncs-evidence.sh` replays the proof through the MNCS toolchain.
 * Any intentional divergence is a bug in this file, never in MNCS source.
 *
 * Remap equivalence note: the integer form
 * `(2*step*to + denom) / (2*denom)` agrees with the legacy float
 * `floor(step / max(1, from) * to + 0.5)` on every product input EXCEPT
 * exact .5 ties. Ties (160 out of 1048385 grid combos over steps 2..128)
 * previously fell wherever two-step float dust landed (always down, as
 * measured); MNCS rounds them up deterministically. This is an intentional
 * normalization toward exactness, evidenced in docs/mncs-pressure.md
 * D-003 — not silent drift. Callers pass array indices and lengths
 * (non-negative integers).
 *
 * `mncsContentBars` is specified, proven, and tested here but NOT
 * delegated on the migration path yet: content ends arrive as float beat
 * sums whose dust near a bar boundary can flip `ceil` after tick
 * rounding. See docs/mncs-pressure.md item P-007.
 */

import {
  wasmFirst,
  wasmMigrateAutoScratchUpgrade,
  wasmMigrateContentBars,
  wasmMigrateLegacyNumerator,
  wasmMigrateNormalizeOctave,
  wasmMigrateNormalizeRoot,
  wasmMigrateRemapCell,
  wasmMigrateRemapIndex,
} from './mncsWasm';

/** MNCS `legacy_numerator`: integer beatsPerBar 1..32, else -1 (host uses 4/4). */
export function mncsLegacyNumerator(beats: number): number {
  // WASM answers null on the -1 sentinel; the fallback owns the -1.
  return wasmFirst('legacy_numerator', wasmMigrateLegacyNumerator(beats), () => (
    Number.isInteger(beats) && beats >= 1 && beats <= 32 ? beats : -1
  ));
}

/**
 * MNCS `remap_index`: round-half-up(step * to / from) clamped into
 * [0, to - 1]. Precondition: non-negative integer step (array index).
 */
export function mncsRemapIndex(step: number, fromSteps: number, toSteps: number): number {
  return wasmFirst('remap_index', wasmMigrateRemapIndex(step, fromSteps, toSteps), () => {
    const denom = fromSteps < 1 ? 1 : fromSteps;
    // Math.trunc mirrors MNCS `/` truncation exactly (negative parity
    // verified); `<= 0` also normalizes -0 to 0 (integers have no -0).
    const scaled = Math.trunc((2 * step * toSteps + denom) / (2 * denom));
    if (toSteps < 1) return 0;
    const cap = toSteps - 1;
    if (scaled <= 0) return 0;
    if (scaled > cap) return cap;
    return scaled;
  });
}

/** MNCS `remap_cell`: stronger hit wins collisions. */
export function mncsRemapCell(existing: number, incoming: number): number {
  return wasmFirst('remap_cell', wasmMigrateRemapCell(existing, incoming), () => (
    existing >= incoming ? existing : incoming
  ));
}

/**
 * MNCS `content_bars`: ceil(contentTicks / meterTicks), 0 for empty
 * content, 1 for a degenerate meter. The caller clamps via
 * `mncsClampMotifBars`.
 */
export function mncsContentBars(contentTicks: number, meterTicks: number): number {
  return wasmFirst('content_bars', wasmMigrateContentBars(contentTicks, meterTicks), () => {
    if (meterTicks <= 0) return 1;
    if (contentTicks <= 0) return 0;
    return Math.trunc((contentTicks + meterTicks - 1) / meterTicks);
  });
}

/** MNCS `normalize_root`: pitch class 0..11. */
export function mncsNormalizeRoot(root: number): number {
  return wasmFirst('normalize_root', wasmMigrateNormalizeRoot(root), () => ((root % 12) + 12) % 12);
}

/** MNCS `normalize_octave`: key-octave clamp into 1..6. */
export function mncsNormalizeOctave(octave: number): number {
  return wasmFirst('normalize_octave', wasmMigrateNormalizeOctave(octave), () => {
    if (octave < 1) return 1;
    if (octave > 6) return 6;
    return octave;
  });
}

/** MNCS `auto_scratch_upgrade`: v3+ respects the stored flag, older upgrades to ON. */
export function mncsAutoScratchUpgrade(isV3OrLater: boolean, storedFlag: boolean): boolean {
  return wasmFirst(
    'auto_scratch_upgrade',
    wasmMigrateAutoScratchUpgrade(isV3OrLater, storedFlag),
    () => (isV3OrLater ? storedFlag : true),
  );
}
