/**
 * TypeScript projection of `mncs/wav.mncs` (`scratchtrack.wav.v1`).
 *
 * Exact integer WAV/PCM-container math: 16-bit mono PCM header fields at
 * MNCS-owned offsets, validity policy, size laws, and leading-magic
 * classification codes. Byte access (`DataView`, `Uint8Array`) and float
 * sample scaling stay host-side at the boundary; magic codes cross as
 * integers (1 = WAV, 2 = WebM, 3 = MP4, 4 = Ogg, 0 = unknown) and the host
 * combines them with the length/mime rules it already owns (MNCS has no
 * strings yet).
 *
 * Every kernel runs its compiled MNCS function WASM-first (via
 * `wasmFirst`) with the pure body below as the conformance-pinned
 * fallback. Window-taking kernels slice the semantically-correct fixed
 * window (44-byte header, 12-byte magic) out of the host buffer and
 * stage it as a canonical cell; when fewer bytes remain than the window
 * needs, the pure body runs instead (same value — the window only ever
 * adds unread bytes). MNCS is the semantic authority: `mncs/wav.mncs`
 * plus `mncs/wav-corpus.json` (generated by `scripts/mncs-wav-corpus.py`)
 * define the contract, `src/mncsWav.test.ts` pins every corpus vector in
 * this suite, and `scripts/mncs-evidence.sh` replays the proof through
 * the MNCS toolchain. Any intentional divergence is a bug in this file,
 * never in MNCS source.
 */

import {
  wasmFirst,
  wasmWavBitsSupported,
  wasmWavByteRate,
  wasmWavDataSizeForSamples,
  wasmWavDecodable,
  wasmWavLeU16,
  wasmWavLeU32,
  wasmWavMagicCode,
  wasmWavRiffChunkSize,
  wasmWavSampleCount,
} from './mncsWasm';

/** Canonical 16-bit mono PCM WAV field offsets. */
export const WAV_FORMAT_OFFSET = 20;
export const WAV_CHANNELS_OFFSET = 22;
export const WAV_SAMPLE_RATE_OFFSET = 24;
export const WAV_BITS_OFFSET = 34;
export const WAV_DATA_SIZE_OFFSET = 40;
export const WAV_HEADER_SIZE = 44;

/** MNCS `magic_code` results (plain values: erasable-syntax codebase). */
export type WavMagic = 0 | 1 | 2 | 3 | 4;
export const WavMagic = {
  Unknown: 0,
  Wav: 1,
  Webm: 2,
  Mp4: 3,
  Ogg: 4,
} as const;

/** Slice `len` bytes at `at` (null when the buffer ends first). */
function sliceWindow(view: DataView, at: number, len: number): Uint8Array | null {
  if (at < 0 || at + len > view.byteLength) return null;
  return new Uint8Array(view.buffer, view.byteOffset + at, len);
}

/** MNCS `le_u16_at` / `le_u32_at`: explicit little-endian decoding. */
export function mncsLeU16(view: DataView, offset: number): number {
  const window = sliceWindow(view, offset, WAV_HEADER_SIZE);
  return wasmFirst('le_u16_at', window ? wasmWavLeU16(window, 0) : null, () => (
    view.getUint8(offset) + view.getUint8(offset + 1) * 256
  ));
}

export function mncsLeU32(view: DataView, offset: number): number {
  const window = sliceWindow(view, offset, WAV_HEADER_SIZE);
  return wasmFirst('le_u32_at', window ? wasmWavLeU32(window, 0) : null, () => (
    view.getUint8(offset) +
    view.getUint8(offset + 1) * 256 +
    view.getUint8(offset + 2) * 65536 +
    view.getUint8(offset + 3) * 16777216
  ));
}

/** MNCS `wav_format_tag` / channels / sample rate / bits / data size. */
export function mncsWavFormatTag(view: DataView): number {
  return mncsLeU16(view, WAV_FORMAT_OFFSET);
}

export function mncsWavChannels(view: DataView): number {
  return mncsLeU16(view, WAV_CHANNELS_OFFSET);
}

export function mncsWavSampleRate(view: DataView): number {
  return mncsLeU32(view, WAV_SAMPLE_RATE_OFFSET);
}

export function mncsWavBitsPerSample(view: DataView): number {
  return mncsLeU16(view, WAV_BITS_OFFSET);
}

export function mncsWavDataSize(view: DataView): number {
  return mncsLeU32(view, WAV_DATA_SIZE_OFFSET);
}

/**
 * MNCS `header_magic_ok`: 'RIFF' at 0..3 and 'WAVE' at 8..11.
 * Precondition: at least 12 bytes (the host guards length first).
 * The 12-byte `magic_code == 1` arm reads exactly these bytes, so the
 * WASM path stages the first 12 whenever present.
 */
export function mncsWavMagicOk(bytes: Uint8Array): boolean {
  // A compiled verdict over the first 12 bytes is authoritative for the
  // WAV question (the arm reads exactly these bytes); only an
  // unstaged/failed call falls back.
  const wasm = bytes.length >= 12 ? wasmWavMagicCode(bytes.subarray(0, 12)) : null;
  return wasmFirst('magic_code', wasm === null ? null : wasm === 1, () => (
    bytes[0] === 0x52 &&
    bytes[1] === 0x49 &&
    bytes[2] === 0x46 &&
    bytes[3] === 0x46 &&
    bytes[8] === 0x57 &&
    bytes[9] === 0x41 &&
    bytes[10] === 0x56 &&
    bytes[11] === 0x45
  ));
}

/**
 * MNCS `header_decodable`: full 16-bit mono PCM policy.
 * Precondition: at least 44 bytes.
 */
export function mncsWavDecodable(view: DataView, bytes: Uint8Array): boolean {
  const header = bytes.length >= WAV_HEADER_SIZE ? bytes.subarray(0, WAV_HEADER_SIZE) : null;
  return wasmFirst('header_decodable', header ? wasmWavDecodable(header) : null, () => (
    mncsWavMagicOk(bytes) &&
    mncsWavFormatTag(view) === 1 &&
    mncsWavChannels(view) === 1 &&
    mncsWavBitsPerSample(view) === 16
  ));
}

/** MNCS `bits_supported`: the decoder's second error arm. */
export function mncsWavBitsSupported(bits: number): boolean {
  return wasmFirst('bits_supported', wasmWavBitsSupported(bits), () => bits === 16);
}

/** MNCS `wav_sample_count`: 2 bytes per mono sample. */
export function mncsWavSampleCount(dataSize: number): number {
  return wasmFirst('wav_sample_count', wasmWavSampleCount(dataSize), () => Math.floor(dataSize / 2));
}

/** MNCS `wav_riff_chunk_size`: 36 + data (RIFF size field semantics). */
export function mncsWavRiffChunkSize(dataSize: number): number {
  return wasmFirst('wav_riff_chunk_size', wasmWavRiffChunkSize(dataSize), () => 36 + dataSize);
}

/** MNCS `wav_data_size_for_samples`. */
export function mncsWavDataSizeForSamples(samples: number): number {
  return wasmFirst('wav_data_size_for_samples', wasmWavDataSizeForSamples(samples), () => samples * 2);
}

/** MNCS `wav_byte_rate`: 2 bytes per sample for 16-bit mono. */
export function mncsWavByteRate(sampleRate: number): number {
  return wasmFirst('wav_byte_rate', wasmWavByteRate(sampleRate), () => sampleRate * 2);
}

/**
 * MNCS `magic_code` over the first 12 bytes. Length guards mirror the
 * legacy arms exactly: EBML/Ogg need 4 bytes, ftyp needs 8, WAV needs 12.
 * With 12+ bytes present the compiled check reads the same bytes, so the
 * WASM path stages the first 12; shorter inputs stay on the guarded
 * pure arms.
 */
export function mncsMagicCode(bytes: Uint8Array): WavMagic {
  const wasm = bytes.length >= 12 ? wasmWavMagicCode(bytes.subarray(0, 12)) : null;
  return wasmFirst<WavMagic>('magic_code', wasm as WavMagic | null, () => {
    if (bytes.length >= 12 && mncsWavMagicOk(bytes)) return WavMagic.Wav;
    if (
      bytes.length >= 4 &&
      bytes[0] === 0x1a &&
      bytes[1] === 0x45 &&
      bytes[2] === 0xdf &&
      bytes[3] === 0xa3
    ) {
      return WavMagic.Webm;
    }
    if (
      bytes.length >= 8 &&
      bytes[4] === 0x66 &&
      bytes[5] === 0x74 &&
      bytes[6] === 0x79 &&
      bytes[7] === 0x70
    ) {
      return WavMagic.Mp4;
    }
    if (
      bytes.length >= 4 &&
      bytes[0] === 0x4f &&
      bytes[1] === 0x67 &&
      bytes[2] === 0x67 &&
      bytes[3] === 0x53
    ) {
      return WavMagic.Ogg;
    }
    return WavMagic.Unknown;
  });
}
