/**
 * TypeScript projection of `mncs/pack.mncs` (`scratchtrack.pack.v1`).
 *
 * Exact integer ZIP-store layout math: fixed-field offsets, sizes,
 * signatures, and entry-walk arithmetic for the uncompressed project
 * pack. Byte access stays host-side at the boundary; iteration over
 * dynamic structures (backward EOCD scan, per-entry walk) stays
 * host-side too (see P-009 in docs/mncs-pressure.md). Checksums moved
 * to the MNCS CRC model (`mncs/crc.mncs` / `mncsCrc.ts`), which the
 * pack writer delegates to.
 *
 * MNCS is the semantic authority: `mncs/pack.mncs` plus
 * `mncs/pack-corpus.json` (generated by `scripts/mncs-pack-corpus.py`)
 * define the contract, `src/mncsPack.test.ts` pins every corpus vector in
 * this suite, and `scripts/mncs-evidence.sh` replays the proof through
 * the MNCS toolchain. Any intentional divergence is a bug in this file,
 * never in MNCS source.
 */

/** Structured central-directory entry: mirrors MNCS record `Entry`. */
export interface PackEntry {
  nameLen: number;
  extraLen: number;
  commentLen: number;
  localOffset: number;
  dataSize: number;
  crc: number;
}

/** ZIP signatures (little-endian u32). */
export const ZIP_LOCAL_SIGNATURE = 0x04034b50;
export const ZIP_CENTRAL_SIGNATURE = 0x02014b50;
export const ZIP_EOCD_SIGNATURE = 0x06054b50;

/** Fixed record sizes. */
export const ZIP_LOCAL_HEADER_SIZE = 30;
export const ZIP_CENTRAL_HEADER_SIZE = 46;
export const ZIP_EOCD_SIZE = 22;

/** MNCS `le16_46` / `le32_46` / `le16_22` / `le32_22`. */
export function mncsPackLe16(view: DataView, offset: number): number {
  return view.getUint8(offset) + view.getUint8(offset + 1) * 256;
}

export function mncsPackLe32(view: DataView, offset: number): number {
  return (
    view.getUint8(offset) +
    view.getUint8(offset + 1) * 256 +
    view.getUint8(offset + 2) * 65536 +
    view.getUint8(offset + 3) * 16777216
  );
}

/** MNCS `local_signature_ok`. Precondition: window holds 46 bytes at offset. */
export function mncsLocalSignatureOk(view: DataView, offset: number): boolean {
  return mncsPackLe32(view, offset) === ZIP_LOCAL_SIGNATURE;
}

/** MNCS `local_name_len` / `local_extra_len` / `local_data_size`. */
export function mncsLocalNameLen(view: DataView, offset: number): number {
  return mncsPackLe16(view, offset + 26);
}

export function mncsLocalExtraLen(view: DataView, offset: number): number {
  return mncsPackLe16(view, offset + 28);
}

export function mncsLocalDataSize(view: DataView, offset: number): number {
  return mncsPackLe32(view, offset + 22);
}

/** MNCS `local_data_start`: header (30) plus variable name/extra runs. */
export function mncsLocalDataStart(localOffset: number, nameLen: number, extraLen: number): number {
  return localOffset + ZIP_LOCAL_HEADER_SIZE + nameLen + extraLen;
}

/** MNCS `local_record_size`: header + name + data (write path). */
export function mncsLocalRecordSize(nameLen: number, dataLen: number): number {
  return ZIP_LOCAL_HEADER_SIZE + nameLen + dataLen;
}

/** MNCS `central_signature_ok`. */
export function mncsCentralSignatureOk(view: DataView, offset: number): boolean {
  return mncsPackLe32(view, offset) === ZIP_CENTRAL_SIGNATURE;
}

/** MNCS `central_entry`: structured parse of one central entry. */
export function mncsCentralEntry(view: DataView, offset: number): PackEntry {
  return {
    nameLen: mncsPackLe16(view, offset + 28),
    extraLen: mncsPackLe16(view, offset + 30),
    commentLen: mncsPackLe16(view, offset + 32),
    localOffset: mncsPackLe32(view, offset + 42),
    dataSize: mncsPackLe32(view, offset + 24),
    crc: mncsPackLe32(view, offset + 16),
  };
}

/** MNCS `central_next`: next entry position past the variable runs. */
export function mncsCentralNext(central: number, nameLen: number, extraLen: number, commentLen: number): number {
  return central + ZIP_CENTRAL_HEADER_SIZE + nameLen + extraLen + commentLen;
}

/** MNCS `central_record_size`: header + name (write path). */
export function mncsCentralRecordSize(nameLen: number): number {
  return ZIP_CENTRAL_HEADER_SIZE + nameLen;
}

/** MNCS `eocd_signature_ok`. */
export function mncsEocdSignatureOk(view: DataView, offset: number): boolean {
  return mncsPackLe32(view, offset) === ZIP_EOCD_SIGNATURE;
}

/** MNCS `eocd_count` / `eocd_central_size` / `eocd_central_offset`. */
export function mncsEocdCount(view: DataView, offset: number): number {
  return mncsPackLe16(view, offset + 10);
}

export function mncsEocdCentralSize(view: DataView, offset: number): number {
  return mncsPackLe32(view, offset + 12);
}

export function mncsEocdCentralOffset(view: DataView, offset: number): number {
  return mncsPackLe32(view, offset + 16);
}
