/**
 * TypeScript projection of `mncs/text.mncs` (`scratchtrack.text.v1`).
 *
 * Strict machine-native parse direction for `bar.beat.sixteenth`
 * position text: the host trims and encodes to bytes (text *production* —
 * `formatPosition`, note names, labels — stays host-side because MNCS has
 * no owned text value type; see P-002), and MNCS owns digit scanning,
 * part structure, defaults, validity, and tick computation.
 *
 * MNCS is the semantic authority: `mncs/text.mncs` plus
 * `mncs/text-corpus.json` (generated by `scripts/mncs-text-corpus.py`)
 * define the contract, `src/mncsText.test.ts` pins every corpus vector in
 * this suite, and `scripts/mncs-evidence.sh` replays the proof through
 * the MNCS toolchain. Any intentional divergence is a bug in this file,
 * never in MNCS source.
 *
 * Normalization differences vs the legacy `Number()`-based path
 * (evidenced in D-007): surrounding whitespace beyond trim, `Number()`
 * spellings (`0x10`, `1e3`, `Infinity`), and whitespace-as-delimiter are
 * rejected (null) rather than coerced; digit runs past u64 wrap. Strict
 * digit/dot inputs behave identically, exactly.
 */

import { wasmFirst, wasmTextParsePosition, wasmTextPositionTicks } from './mncsWasm';

/** Strict position parts: mirrors MNCS record `Position` (valid only). */
export interface PositionParts {
  bar: number;
  beat: number;
  sixth: number;
}

const ASCII_0 = 48;
const ASCII_9 = 57;
const ASCII_DOT = 46;

function isDigit(byte: number): boolean {
  return byte >= ASCII_0 && byte <= ASCII_9;
}

/**
 * MNCS `parse_position`: fold bytes into parts. Returns null for any
 * non-digit/non-dot byte, a fourth part, or over-long input.
 */
export function mncsParsePositionText(text: string): PositionParts | null {
  return wasmFirst('parse_position', wasmTextParsePosition(text), () => {
    const bytes = new TextEncoder().encode(text);
    if (bytes.length > 64) return null;
    let dot = 0;
    let current = 0;
    let first = 0;
    let second = 0;
    let valid = true;
    for (const value of bytes) {
      if (isDigit(value)) {
        current = current * 10 + (value - ASCII_0);
      } else if (value === ASCII_DOT) {
        if (dot >= 2) {
          valid = false;
        } else if (dot === 0) {
          first = current;
          dot = 1;
        } else {
          second = current;
          dot = 2;
        }
        current = 0;
      } else {
        valid = false;
      }
      // No early exit: MNCS folds the whole view before judging validity.
    }
    if (!valid) return null;
    if (dot === 0) return { bar: current, beat: 1, sixth: 0 };
    if (dot === 1) return { bar: first, beat: current, sixth: 0 };
    return { bar: first, beat: second, sixth: current };
  });
}

/**
 * MNCS `position_ticks`: whole-timeline ticks for strict parts under a
 * bar of `barTicks` ticks, or -1 when out of range (bar/beat floored at
 * 1, sixteenths clamped to 0..3, TOTAL_BEATS cap).
 */
export function mncsPositionTicks(bar: number, beat: number, sixth: number, barTicks: number): number {
  // WASM answers null on the -1 sentinel; the fallback owns the -1.
  return wasmFirst('position_ticks', wasmTextPositionTicks(bar, beat, sixth, barTicks), () => {
    const wholeBar = bar < 1 ? 1 : Math.trunc(bar);
    const wholeBeat = beat < 1 ? 1 : Math.trunc(beat);
    const clampedSixth = sixth > 3 ? 3 : Math.trunc(sixth);
    if ((wholeBeat - 1) * 24 >= barTicks) return -1;
    const ticks = (wholeBar - 1) * barTicks + (wholeBeat - 1) * 24 + clampedSixth * 6;
    const cap = 64 * 24 + barTicks;
    if (ticks > cap) return -1;
    return Math.min(64 * 24, ticks);
  });
}
